project:
  code: "RR771"
  name: "Deciphering the clinical and genetic landscape of patients with germline DHX34 variants"
  start_date: "16-07-2025"
  author: 
    name: "dmouzo"
    contact: "gp241615@qmul.ac.uk"
  genome: "GRCh38"
  github: "https://github.com/damouzo/RR771-DHX34"

# Rutas base del proyecto
base_paths:
  data_root: "/data/BCI-KRP/projects/RR771-DHX34"
  output_root: "/data/BCI-KRP/projects/RR771-DHX34"

# Rutas relativas (se combinarán con base_paths)
paths:
  data:
    raw_data: "data/raw_data"
    processed: "data/processed"
    smallvar_annot: "data/raw_data/WGS_Variants/smallVar"
    structvar_annot: "data/raw_data/WGS_Variants/structuralVar"
    reference:
      protein: "data/reference/Protein"
      exon: "data/reference/Exon"
  output:
    results: "results"
    logs: "results/pipeline_info/logs"
  work: "/data/scratch/qp241615/work"


# Archivos específicos
files:
  gene_list: "data/gene_list.txt"

# Configuración de recursos
resources:
  default:
    cpus: 2
    memory: "8 GB"
    time: "2h"
  high_mem:
    cpus: 8
    memory: "16 GB"
    time: "8h"

# Configuración externa
external:
  labkey_project: 
    main: "/main-programme/main-programme_v19_2024-10-31"
    nhs-gms: "unknown"

# Configuración específica del entorno
environment:
  type: "apocrita"
  executor: "sge"
