project:
  code: "RR771"
  name: "Deciphering the clinical and genetic landscape of patients with germline DHX34 variants"
  start_date: "16-07-2025"
  author: 
    name: "dmouzo"
    contact: "gp241615@qmul.ac.uk"
  genome: "GRCh38"
  github: "https://github.com/damouzo/RR771-DHX34"

# Rutas base del proyecto
base_paths:
  data_root: "/nas/weka.gel.zone/re_gecip/shared_allGeCIPs/dmouzo/RR771"
  output_root: "/nas/weka.gel.zone/re_gecip/shared_allGeCIPs/dmouzo/RR771"

# Rutas relativas (se combinarán con base_paths)
paths:
  data:
    raw_data: "data/raw_data"
    processed: "data/processed"
    smallvar_annot: "data/raw_data/WGS_Variants/250807_small_variant_100K_DDX41_DHX34/results"
    structvar_annot: "data/raw_data/WGS_Variants/250812_structural_variant/results"
    reference:
      protein: "data/reference/Protein"
      exon: "data/reference/Exon"
  output:
    results: "results"
    logs: "results/pipeline_info/logs"
  work: "/nas/weka.gel.zone/re_scratch/re_gecip/cancer_haem/dmouzo"


# Archivos específicos
files:
  gene_list: "conf/small_struct_var_qc/gene_list.txt"

# Configuración de recursos
resources:
  default:
    cpus: 2
    memory: "2 GB"
    time: "1h"
  high_mem:
    cpus: 3
    memory: "4 GB"
    time: "4h"

# Configuración externa
external:
  libPath: "/tools/aws-workspace-apps/ce/R/4.0.2"  # Default R in the system
  labkey_project: 
    main: "main-programme_v19_2024-10-31"
    nhs-gms: "unknown"

# Configuración específica del entorno
environment:
  type: "genomics_england"
  executor: "local"
 