project:
  code: "RR771"
  name: "Deciphering the clinical and genetic landscape of patients with germline DHX34 variants"
  start_date: "16-07-2025"
  author: 
    name: "dmouzo"
    contact: "gp241615@qmul.ac.uk"
  genome: "GRCh38"
  github: "https://github.com/damouzo/RR771-DHX34"

# Rutas base del proyecto
base_paths:
  data_root: "/mnt/c/Users/qp241615/OneDrive - Queen Mary, University of London/Documents/4. Projects/1. DHX34"
  output_root: "/mnt/c/Users/qp241615/OneDrive - Queen Mary, University of London/Documents/4. Projects/1. DHX34"

# Rutas relativas (se combinarán con base_paths)
paths:
  data:
    raw_data: "data/raw_data"
    processed: "data/processed"
    smallvar_annot: "data/raw_data/WGS_Variants/smallVar"
    structvar_annot: "data/raw_data/WGS_Variants/structuralVar"
    reference:
      protein: "data/reference/Protein"
      exon: "data/reference/Exon"
  output:
    results: "results"
    logs: "results/pipeline_info/logs"
    work: "work"


# Archivos específicos
files:
  gene_list: "data/gene_list.txt"

# Configuración de recursos
resources:
  default:
    cpus: 1
    memory: "2 GB"
    time: "1h"
  high_mem:
    cpus: 3
    memory: "4 GB"
    time: "4h"

# Configuración externa
external:
  libPath: null  # Default R in the system
  labkey_project: 
    main: "main-programme_v19_2024-10-31"
    nhs-gms: "unknown"

# Configuración específica del entorno
environment:
  type: "local"
  executor: "local"
